services:
  - type: web
    name: thanospherebot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8165847651:AAFV2hSyWVy2pqcCm60yOisZU3Qs1w67e0E
      - key: WEATHER_API_KEY
        value: 6b33fb715ddedc97349b1a50057cfa73
      - key: GEMINI_API_KEY
        value: AIzaSyDlN2UBt6i8-uhJkSbL0XEKyU9IhKmZOoU
  