services:
  - type: web
    name: thanossphere-weather-bot
    env: python
    region: oregon  # or choose closest to your users
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: WEATHER_API_KEY
        value: your_openweather_api_key_here
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com/webhook
